import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Script id="strip-browser-injected-attrs" strategy="beforeInteractive">
          {`
            (() => {
              const ATTRS = ["bis_skin_checked"];
              const removeAttrs = (root) => {
                for (const attr of ATTRS) {
                  if (root instanceof Element && root.hasAttribute(attr)) {
                    root.removeAttribute(attr);
                  }
                  if (root.querySelectorAll) {
                    root.querySelectorAll("[" + attr + "]").forEach((el) => el.removeAttribute(attr));
                  }
                }
              };

              removeAttrs(document.documentElement);

              const observer = new MutationObserver((mutations) => {
                for (const mutation of mutations) {
                  if (mutation.type === "attributes" && mutation.target) {
                    removeAttrs(mutation.target);
                  }
                  mutation.addedNodes.forEach((node) => removeAttrs(node));
                }
              });

              observer.observe(document.documentElement, {
                subtree: true,
                childList: true,
                attributes: true,
                attributeFilter: ATTRS,
              });
            })();
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
